#pragma once

#include "llvm/Support/CommandLine.h"

#define INSTRUMENTSTAGE_ENUM_PA                 \
        ,                                       \
        Refine,                                 \
        Core

#define INSTRUMENTSTAGE_CL_ENUM_PA              \
        clEnumVal(Onnx, "Profile for onnx ops."),\
        clEnumVal(Refine, "PA profiling for onnx and ops supported by prototype hardware."),\
        clEnumVal(Core, "PA profiling for hardware device driver runtime")

#define PROFILEIR_CL_ENUM_PA                    \
        , clEnumVal(Refine, "Profile operations in RefineIR generated by " \
                            "--EmitRefineIR") \
        , clEnumVal(Core, "Profile operations in RefineIR generated by " \
                          "--EmitCoreIR") \

namespace onnx_mlir {
typedef enum {
    EmitRefineIR,
    EmitCoreIR,
    EmitPNONE,
}PAEmissionTargetType;

extern llvm::cl::OptionCategory OnnxMlirOptions;
extern llvm::cl::opt<onnx_mlir::PAEmissionTargetType> paEmissionTarget;
extern llvm::cl::list<std::string> execNodesOnCpu;
extern llvm::cl::opt<bool> paEnableRefineToOnnx;
extern llvm::cl::opt<bool> profileRefineIR;
extern llvm::cl::opt<bool> profileCoreIR;

} // namespace onnx_mlir
